final/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PertanyaanController;

Route::get('/master', function () {
    return view('partials.master');
});

Route::get('/', 'indexController@rumah');


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('profile', 'ProfilController@edit')->name('profile.edit');
});
Route::group(['middleware' => 'auth'], function () {

    Route::get('profile', 'ProfilController@edit')
        ->name('profile.edit');

    Route::patch('profile', 'ProfilController@update')
        ->name('halaman.profil');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/regis', function(){
    return view('regis');
});

Route::get('/kategori', 'indexController@kategori');
Route::post('/kategori', 'indexController@store');
Route::get('/dashboard', 'indexController@dash');
Route::get('/profil', 'indexController@profil');
Route::get('/ask', 'indexController@ask');
Route::get('/answer', 'indexController@ans');
Route::post('/answer', 'indexController@balas');


// CRUD Kategori
// Route::get('/kategori/create', 'KategoriController@create');
// Route::post('/kategori', 'KategoriController@store');
// Route::get('/kategori', 'KategoriController@index');
// Route::get('/kategori/{kategori_id}', 'KategoriController@show');
// Route::get('/kategori/{kategori_id}/edit', 'KategoriController@edit');
// Route::put('/kategori/{kategori_id}', 'KategoriController@update');
// Route::delete('/kategori/{kategori_id}', 'KategoriController@destroy');

// CRUD pertanyaan

Route::get('/post', function () {
    return redirect('/posts');
});
Route::resource('posts', PostController::class);

final/resources/views/ask/create.blade.php
@extends('partials.master')

@section('title')
Pertanyaan
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Post</h2>
        </div>
        
    </div>
</div>
     
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     
<form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <input type="text" name="title" class="form-control" placeholder="Post Title" value="{{ old('title') }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Body:</strong>
                <textarea class="form-control" name="body" placeholder="Post Body">{{ old('body') }}</textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image:</strong>
                <input type="file" name="image" class="form-control" placeholder="Post Image">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Add Post</button>
        </div>
    </div>
     
</form>
@endsection